### ISSUE TITLE
Game speed settings?

### ISSUE THREAD

**Issue by KixPanganiban** [ericoporto/fgmk#2]
The demo game feels too fast for me. It's like playing a NES game on 2x speed. Any way to change that in-browser?

Google Chrome Version 53.0.2785.116 (64-bit)
macOS Sierra

**Comment by ericoporto** [comment]
Try the following, using f12 (to load the console), type:

    engine.step = 2

I will add an option in the menu to allow setting the base steps (this will half the walking speed for everything, the default is 4).

**Comment by KixPanganiban** [comment]
Yeah, that seems to do the trick! Awesome work!

**Comment by ericoporto** [comment]
Thank you! 

I am writing docs. Hopefully I will have documentation this week!

**Comment by KixPanganiban** [comment]
Awesome. Would love to try making my own game soon. Good luck!
